services:
  frontend:
    image: ${FRONTEND_IMAGE}
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-stage.rule=Host(`stage.self-dev.tech`)"
      - "traefik.http.routers.frontend-stage.entrypoints=websecure"
      - "traefik.http.routers.frontend-stage.tls.certresolver=le"
      - "traefik.http.services.frontend-stage.loadbalancer.server.port=80"

networks:
  self-dev-network:
    external: true