name: self-dev

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - self-dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`self-dev.tech`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"


networks:
  self-dev:
    name: "self-dev"
    external: true
