name: self-dev

services:
  backend:
    image: ${BACKEND_IMAGE}
    restart: unless-stopped
    volumes:
      - .env:/app/.env:ro
    networks:
      - self-dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.self-dev.tech`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"


networks:
  self-dev:
    name: "self-dev"
    external: true