name: self-dev-stage

services:
  auth:
    image: casbin/casdoor:latest
    restart: unless-stopped
    environment:
      - GIN_MODE=release
    volumes:
      - "./auth/conf:/conf"
      - "./auth/logs:/logs"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.stage.self-dev.tech`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=le"
      - "traefik.http.services.auth.loadbalancer.server.port=8000"
    networks:
      - proxy
      - self-dev
    depends_on:
      db:
        condition: service_healthy

  backend:
    image: ghcr.io/selfdevcomp/backend:bd0c1b85169bf3ef321f4509cd4bb4f0446e24eb
    restart: unless-stopped
    volumes:
      - .env.stage:/app/.env:ro
    networks:
      - proxy
      - self-dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.stage.self-dev.tech`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ghcr.io/selfdevcomp/frontend:7b0f028fd4678da7cb7213476f4768630334e584
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`stage.self-dev.tech`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  db:
    image: postgres:18-alpine
    networks:
      - self-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "postgres-data:/var/lib/postgresql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d self-dev"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    networks:
      - self-dev
    volumes:
      - "redis-data:/data"

  migrate:
    image: ghcr.io/selfdevcomp/backend:bd0c1b85169bf3ef321f4509cd4bb4f0446e24eb
    profiles:
      - tools
    entrypoint:
      - goose
    command:
      - -dir
      - /app/migrations
      - postgres
      - postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - up
    networks:
      - self-dev
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres-data:
    name: "self-dev-stage-postgres-volume"
  redis-data:
    name: "self-dev-stage-redis-volume"
  letsencrypt:
    name: "self-dev-stage-letsencrypt"

networks:
  proxy:
    external: true

  self-dev:
    name: "self-dev-stage-network"
    driver: bridge
